#
#Mon Apr 14 11:02:42 BRT 2025
caminho.commictagger=
caminho.legenda=C\:\\Users\\Jhonny\\Desktop\\legenda.csv
caminho.mysql=
caminho.ultimo_salvo_arquivo=C\:\\Users\\Jhonny\\Desktop\\legenda.csv
connection.database=processa_texto
connection.password=admin
connection.port=3306
connection.server=localhost
connection.user=admin
