CREATE TABLE _sql
(
    sequencial  int NOT NULL AUTO_INCREMENT,
    tipo        enum ('INSERT','SELECT','CREATE','UPDATE') DEFAULT NULL,
    descricao   varchar(250)                               DEFAULT NULL,
    texto       longtext,
    atualizacao datetime                                   DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (sequencial)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb3;

insert into _ sql (sequencial, tipo, descricao, texto, atualizacao)
values
    (1, 'SELECT', 'Validar a diferença de tempo', '\r\n\r\nSELECT\r\n  TB.*, \r\n  AUX.Segundo, \r\n  TIMESTAMPDIFF(SECOND,TB.TempoFinal,Aux.TempoInicial)\r\nFROM\r\n  amagami_ss TB\r\n LEFT JOIN amagami_ss AUX\r\n ON (TB.Sequencial  + 1) = AUX.sequencial \r\n \r\nWHERE TB.Linguagem = \"PT\"\r\n\r\nORDER BY Sequencial', '2023-08-06 17:10:11'),
    (2, 'SELECT', 'Selecionar as falas e unir com o portugues', 'SELECT * FROM (\r\nSELECT CONCAT(\"Amagami SS - Episódio 22 - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS ID , JP.Audio, JP.Imagem, JP.Texto AS Expression, EN.Texto AS English, PT.Texto AS Portuguese FROM amagami_ss JP\r\nLEFT JOIN amagami_ss EN ON\r\n  JP.Episodio = EN.Episodio\r\n AND EN.Linguagem = \"EN\"\r\n AND (TIMESTAMPDIFF(SECOND, TIME(JP.TempoInicial), TIME(EN.TempoInicial)) <= 0.5\r\n AND TIMESTAMPDIFF(SECOND, TIME(JP.TempoInicial), TIME(EN.TempoInicial)) >= -0.5) \r\nLEFT JOIN amagami_ss PT ON\r\n PT.Episodio = EN.Episodio\r\n AND EN.TempoInicial = PT.TempoInicial\r\n AND PT.Linguagem = \"PT\"\r\n\r\n WHERE JP.episodio = 22 AND JP.linguagem = \"JP\" AND PT.Texto IS NOT NULL\r\n \r\nUNION ALL \r\n\r\nSELECT CONCAT(\"Amagami SS - Episódio 22 - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS ID , JP.Audio, JP.Imagem, JP.Texto AS Expression, EN.Texto AS English, PT.Texto AS Portuguese FROM amagami_ss JP\r\nLEFT JOIN amagami_ss EN ON\r\n  JP.Episodio = EN.Episodio\r\n AND EN.Linguagem = \"EN\"\r\n AND (TIMESTAMPDIFF(SECOND, TIME(JP.TempoInicial), TIME(EN.TempoInicial)) <= 1\r\n AND TIMESTAMPDIFF(SECOND, TIME(JP.TempoInicial), TIME(EN.TempoInicial)) >= -1) \r\nLEFT JOIN amagami_ss PT ON\r\n PT.Episodio = EN.Episodio\r\n AND EN.TempoInicial = PT.TempoInicial\r\n AND PT.Linguagem = \"PT\"\r\n WHERE JP.episodio = 22 AND JP.linguagem = \"JP\" AND PT.Texto IS NOT NULL\r\n \r\n UNION ALL \r\n\r\nSELECT CONCAT(\"Amagami SS - Episódio 22 - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS ID , JP.Audio, JP.Imagem, JP.Texto AS Expression, EN.Texto AS English, PT.Texto AS Portuguese FROM amagami_ss JP\r\nLEFT JOIN amagami_ss EN ON\r\n  JP.Episodio = EN.Episodio\r\n AND EN.Linguagem = \"EN\"\r\n AND (TIMESTAMPDIFF(SECOND, TIME(JP.TempoInicial), TIME(EN.TempoInicial)) <= 2\r\n AND TIMESTAMPDIFF(SECOND, TIME(JP.TempoInicial), TIME(EN.TempoInicial)) >= -2) \r\nLEFT JOIN amagami_ss PT ON\r\n PT.Episodio = EN.Episodio\r\n AND EN.TempoInicial = PT.TempoInicial\r\n AND PT.Linguagem = \"PT\"\r\n WHERE JP.episodio = 22 AND JP.linguagem = \"JP\") AS t\r\n \r\n GROUP BY ID', '2023-08-06 17:10:11'),
    (3, 'UPDATE', 'Correção dos nomes', 'SELECT REPLACE(REPLACE(imagem, \"_\", \" \"), \"00 1 0\", \"00 - 00\") AS Imagem, REPLACE(REPLACE(audio, \"_\", \" \"), \"00 1 0\", \"00 - 00\") AS Audio FROM fate_stay_nigh_unlimited ;\r\n \r\nUPDATE\r\n  fate_stay_nigh_unlimited\r\nSET\r\n  Audio = REPLACE(REPLACE(audio, \"_\", \" \"), \"00 1 0\", \"00 - 00\"),\r\n  Imagem = REPLACE(REPLACE(imagem, \"_\", \" \"), \"00 1 0\", \"00 - 00\"),\r\n  TempoInicial = CONCAT(REPLACE(SUBSTRING(TempoInicial, 1, 8), \".\", \":\"), SUBSTRING(TEMPOiNICIAL,9))\r\n  ;\r\n\r\n\r\nUPDATE\r\n  amagami_ss\r\nSET\r\n  Audio = CONCAT(SUBSTRING(REPLACE(REPLACE(audio, \"_\", \" \"), \"PT 1 0\", \"- 00\"), 1, 46), \".mp3]\"),\r\n  imagem = REPLACE(REPLACE(imagem, \"_\", \" \"), \"PT 1 0\", \"- 00\")', '2023-08-06 17:10:11'),
    (4, 'CREATE', 'Criação da tabela', '\r\n\r\nCREATE TABLE bakemonogatari (\r\n  id VARCHAR(36) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  Episodio INT(2) DEFAULT NULL,\r\n  Linguagem VARCHAR(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  TempoInicial VARCHAR(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  TempoFinal VARCHAR(15) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  Texto LONGTEXT COLLATE utf8mb4_unicode_ci,\r\n  Traducao LONGTEXT COLLATE utf8mb4_unicode_ci,\r\n  Vocabulario LONGTEXT COLLATE utf8mb4_unicode_ci,\r\n  Atualizacao DATETIME DEFAULT CURRENT_TIMESTAMP,\r\n  PRIMARY KEY (id)\r\n) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\r\n\r\n\r\nDELIMITER $$\r\n\r\nCREATE\r\n    /*!50017 DEFINER = \' admin\'@\'%\' */\r\n    TRIGGER bakemonogatari_insert BEFORE INSERT ON bakemonogatari \r\n    FOR EACH ROW BEGIN                                                                                                                                                                                               \r\n	IF (NEW.id IS NULL OR NEW.id = \'\')  THEN                                                                                                                                                                            \r\n		SET new.id = UUID();                                                                                                                                                                                               \r\n	END IF;                                                                                                                                                                                                             \r\n    END;\r\n$$\r\n\r\n\r\nCREATE\r\n    /*!50017 DEFINER = \'admin\'@\'%\' */\r\n    TRIGGER bakemonogatari_update BEFORE UPDATE ON bakemonogatari \r\n    FOR EACH ROW BEGIN                                                                                                                                                    \r\n	IF (OLD.id != NEW.id) OR (OLD.Episodio != NEW.Episodio) OR  (OLD.Linguagem != NEW.Linguagem) OR  (OLD.TempoInicial != NEW.TempoInicial) OR  (OLD.TempoFinal != NEW.TempoFinal) OR  \r\n		(OLD.Texto != NEW.Texto) OR (OLD.Traducao != NEW.Traducao) OR (OLD.Vocabulario != NEW.Vocabulario)   THEN \r\n	SET new.atualizacao = NOW(); \r\n	END IF;                                                                                                                                                \r\n    END;\r\n$$\r\n\r\nDELIMITER ;', '2023-08-06 17:32:09'),
    (5, 'SELECT', 'Select novo para exportação ao deck', 'SELECT CONCAT(\"FateStay Nigth Unlimited Blade Works - Episódio 00 - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS ID , JP.Audio, JP.Imagem, JP.Texto AS Expression, JP.Traducao AS English, PT.Traducao AS Portuguese \r\nFROM decksubtitle.fatestay_night_unlimited JP\r\nLEFT JOIN (SELECT Traducao, Episodio, TempoInicial FROM decksubtitle.fatestay_night_unlimited  WHERE Linguagem = \"PT\" AND Episodio = 0 ) AS PT ON JP.Episodio = PT.Episodio AND JP.TempoInicial = PT.TempoInicial\r\nWHERE JP.Episodio = 0 AND JP.Linguagem = \"EN\";\r\n', '2023-08-06 17:10:11'),
    (6, 'INSERT', 'Importação para a base postbot', 'INSERT INTO postbot.anime (Descricao, Japones, Ingles, Portugues, Anime, Tag, Imagem)\r\nSELECT CONCAT(\"FateStay Nigth Unlimited Blade Works - Episódio \", JP.episodio ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Texto AS Japones, EN.Traducao AS Ingles, JP.Traducao AS Portugues, \"FateStay Night Unlimited Blade Works\" AS Anime, CONCAT(\"FateStayUBW Anime Episódio\", JP.Episodio) AS Tag,\r\n REPLACE(REPLACE(JP.Imagem, \"<img src=\\\"\", \"\"), \"\\\">\", \"\") AS Imagem\r\nFROM decksubtitle.fatestay_night_unlimited JP\r\nLEFT JOIN (SELECT Traducao, Episodio, TempoInicial FROM decksubtitle.fatestay_night_unlimited  WHERE Linguagem = \"EN\") AS EN ON JP.Episodio = EN.Episodio AND JP.TempoInicial = EN.TempoInicial\r\nWHERE JP.Episodio > 9 AND JP.Episodio < 15 AND JP.Linguagem = \"PT\";', '2023-08-06 17:10:11'),
    (7, 'SELECT', 'Select varios episodios export para anki', 'SELECT CONCAT(\"FateStay Nigth Unlimited Blade Works - Episódio 0\", JP.episodio ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Texto AS Japones, EN.Traducao AS Ingles, JP.Traducao AS Portugues, JP.Imagem AS Imagem, JP.Audio AS Audio\r\nFROM decksubtitle.fatestay_night_unlimited JP\r\nLEFT JOIN (SELECT Traducao, Episodio, TempoInicial FROM decksubtitle.fatestay_night_unlimited  WHERE Linguagem = \"EN\") AS EN ON JP.Episodio = EN.Episodio AND JP.TempoInicial = EN.TempoInicial\r\nWHERE JP.Episodio > 1 AND JP.Episodio < 10 AND JP.Linguagem = \"PT\";\r\n', '2023-08-06 17:10:11'),
    (8, 'SELECT', 'Select all, exportação vocabulário para o anki', '\r\nSELECT CONCAT(\"Amagami SS - Episódio \", LPAD(JP.episodio, 2, 0) ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Vocabulario AS Vocabulario\r\nFROM decksubtitle.amagami_ss JP\r\nWHERE JP.Linguagem = \"PT\" AND JP.Vocabulario IS NOT NULL\r\nUNION ALL\r\nSELECT CONCAT(\"Amagami SS - Episódio \", LPAD(JP.episodio, 2, 0) ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Vocabulario AS Vocabulario\r\nFROM decksubtitle.amagami_ss_antigo JP\r\nWHERE JP.Linguagem = \"JP\" AND JP.Vocabulario IS NOT NULL\r\nUNION ALL\r\nSELECT CONCAT(\"BakeMonogatari - Episódio \", LPAD(JP.episodio, 2, 0) ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Vocabulario AS Vocabulario\r\nFROM decksubtitle.bakemonogatari JP\r\nWHERE JP.Linguagem = \"PT\" AND JP.Vocabulario IS NOT NULL\r\nUNION ALL\r\nSELECT CONCAT(\"FateStay Nigth Unlimited Blade Works - Episódio \", LPAD(JP.episodio, 2, 0) ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Vocabulario AS Vocabulario\r\nFROM decksubtitle.fatestay_night_unlimited JP\r\nWHERE JP.Linguagem = \"PT\" AND JP.Vocabulario IS NOT NULL\r\nUNION ALL\r\nSELECT CONCAT(\"Kakegurui - Episódio \", LPAD(JP.episodio, 2, 0) ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Vocabulario AS Vocabulario\r\nFROM decksubtitle.kakegurui JP\r\nWHERE JP.Linguagem = \"PT\" AND JP.Vocabulario IS NOT NULL\r\nUNION ALL\r\nSELECT CONCAT(\"Mahouka Koukou no Rettousei - Episódio \", LPAD(JP.episodio, 2, 0) ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Vocabulario AS Vocabulario\r\nFROM decksubtitle.mahouka_koukou_no_rettousei JP\r\nWHERE JP.Linguagem = \"PT\" AND JP.Vocabulario IS NOT NULL\r\nUNION ALL\r\nSELECT CONCAT(\"Re:Zero Kara Hajimeru Isekai Seikatsu - Episódio \", LPAD(JP.episodio, 2, 0) ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Vocabulario AS Vocabulario\r\nFROM decksubtitle.re_zero_kara_hajimeru_isekai_seikatsu JP\r\nWHERE JP.Linguagem = \"PT\" AND JP.Vocabulario IS NOT NULL\r\nUNION ALL\r\nSELECT CONCAT(\"Otome Game No Hametsu Flag - Episódio \", LPAD(JP.episodio, 2, 0) ,\" - \", TIME_FORMAT(JP.TempoInicial, \"%H:%i:%s\")) AS Descricao , \r\n JP.Vocabulario AS Vocabulario\r\nFROM decksubtitle.otome_game_no_hametsu JP\r\nWHERE JP.Linguagem = \"PT\" AND JP.Vocabulario IS NOT NULL ORDER BY Descricao', '2023-08-06 17:10:11'),
    (9, 'UPDATE', 'Limpeza vocabulario vazio', 'UPDATE decksubtitle.amagami_ss SET Vocabulario = NULL WHERE Vocabulario = \'\';\r\nUPDATE decksubtitle.amagami_ss_antigo SET Vocabulario = NULL WHERE Vocabulario = \'\';\r\nUPDATE decksubtitle.bakemonogatari SET Vocabulario = NULL WHERE Vocabulario = \'\';\r\nUPDATE decksubtitle.fatestay_night_unlimited SET Vocabulario = NULL WHERE Vocabulario = \'\';\r\nUPDATE decksubtitle.kakegurui SET Vocabulario = NULL WHERE Vocabulario = \'\';\r\nUPDATE decksubtitle.mahouka_koukou_no_rettousei SET Vocabulario = NULL WHERE Vocabulario = \'\';\r\nUPDATE decksubtitle.re_zero_kara_hajimeru_isekai_seikatsu SET Vocabulario = NULL WHERE Vocabulario = \'\';\r\nUPDATE decksubtitle.otome_game_no_hametsu SET Vocabulario = NULL WHERE Vocabulario = \'\';\r\n', '2023-08-06 17:10:11');

CREATE TABLE exemplo
(
    id           varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    Episodio     int                                                          DEFAULT NULL,
    Linguagem    varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    TempoInicial varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    TempoFinal   varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    Texto        longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    Traducao     longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    Vocabulario  longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    Atualizacao  datetime                                                     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
